language: node_js

node_js:
 - 14
 - 12

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm ci
  - npm run cy:verify

script:
  - npm test
  #   ## print all Travis environment variables for debugging
  - $(npm bin)/print-env TRAVIS
  - $(npm bin)/cypress run --project test
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - kill $(jobs -p) || true