language: node_js

node_js:
 - 14
 - 12

cache:
  directories:
    - ~/.npm
    - ~/.cache

override:
  - npm ci
  - npm run cy:verify

defaults: &defaults
  script:
    - npm test
    #   ## print all Travis environment variables for debugging
    - $(npm bin)/print-env TRAVIS
    - npm run start:ci &
    - npm run cy:run -- --record --parallel --group $STAGE_NAME
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true