language: node_js

node_js:
 - 14
 - 12

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - npm install -g wait-on
  - npm ci

before_script:
  - npm run start & wait-on http://localhost:3000

script:
  - npm test
  # run all Cypress tests and record on the dashboard
  - npx cypress run --record --key f8b73633-9e35-4eb4-930b-cf7d913a04f8
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  - npm run build

after_success:
  - npm install -g firebase-tools
  - firebase deploy --token "$FIREBASE_TOKEN"